# addrman-observer configuration file

address = "127.0.0.1:24822"
www_path = "../www"

[[nodes]]

id = 0
rpc_host = "127.0.0.1"
rpc_port = 38332
rpc_cookie_file = "/home/b10c/.bitcoin/signet/.cookie"
#rpc_user = ""
#rpc_password = ""
